#requires -Version 5.1
<#
.SYNOPSIS
    Prepares and launches the Automn runner service on Windows hosts without containers.

.DESCRIPTION
    This script installs production dependencies (unless skipped), gathers the Automn runner
    configuration, and starts the Node.js runner service with the required environment variables.
    Provide parameters directly or allow the script to prompt for missing values. Secrets entered
    interactively are stored only in the runner state file after the service registers.

.PARAMETER HostUrl
    The base URL of the Automn host (for example https://automn.example.com or http://localhost:8088).

.PARAMETER RunnerId
    The identifier generated by the Automn host UI when adding a runner.

.PARAMETER EndpointUrl
    Full URL used by the Automn host to reach this runner (for example http://runner-host:3030/api/run).
    Provide either EndpointUrl or PublicUrl (with optional EndpointPath).

.PARAMETER PublicUrl
    Public base URL for the runner (for example http://runner-host:3030). Requires EndpointPath when set.

.PARAMETER EndpointPath
    Path appended to PublicUrl to form the Automn host endpoint. Defaults to /api/run.

.PARAMETER Port
    Optional port for the runner service. When omitted, the service listens on the default port (3030).

.PARAMETER Secret
    Optional runner secret. When omitted, the runner UI prompts for it during first launch.


.PARAMETER StateDir
    Directory for the runner state file. Defaults to a "state" folder next to this script.

.PARAMETER ScriptsDir
    Directory where generated scripts are stored. Defaults to a "scripts" folder next to this script.

.PARAMETER WorkDir
    Working directory for script execution. Defaults to a "script_workdir" folder next to this script.

.PARAMETER SkipNpmInstall
    Skips running "npm ci --omit=dev". Use when dependencies are already installed.

.EXAMPLE
    .\start-runner.ps1 -HostUrl "https://automn.example.com" -RunnerId "runner-01" -EndpointUrl "https://runner-01.example.com/api/run"

    Launches the runner with the supplied configuration after installing dependencies.
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $false)]
    [string]$HostUrl,

    [Parameter(Mandatory = $false)]
    [string]$RunnerId,

    [Parameter(Mandatory = $false)]
    [string]$EndpointUrl,

    [Parameter(Mandatory = $false)]
    [string]$PublicUrl,

    [Parameter(Mandatory = $false)]
    [string]$EndpointPath = "/api/run",

    [Parameter(Mandatory = $false)]
    [int]$Port,

    [Parameter(Mandatory = $false)]
    [string]$Secret,

    [Parameter(Mandatory = $false)]
    [string]$StateDir,

    [Parameter(Mandatory = $false)]
    [string]$ScriptsDir,

    [Parameter(Mandatory = $false)]
    [string]$WorkDir,

    [Parameter(Mandatory = $false)]
    [string]$NodeExecutable,

    [Parameter(Mandatory = $false)]
    [string]$PythonExecutable,

    [Parameter(Mandatory = $false)]
    [string]$PowerShellExecutable,

    [switch]$SkipNpmInstall
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

function Resolve-RepoRoot {
    param(
        [string]$ScriptPath
    )

    $scriptDirectory = Split-Path -Path $ScriptPath -Parent
    return (Resolve-Path -Path (Join-Path -Path $scriptDirectory -ChildPath "..")).ProviderPath
}

function Get-ValueOrPrompt {
    param(
        [string]$CurrentValue,
        [string]$PromptMessage,
        [switch]$IsSecret
    )

    if ([string]::IsNullOrWhiteSpace($CurrentValue)) {
        if ($IsSecret) {
            $secure = Read-Host -Prompt $PromptMessage -AsSecureString
            $ptr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
            try {
                return [Runtime.InteropServices.Marshal]::PtrToStringBSTR($ptr)
            }
            finally {
                [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($ptr)
            }
        }

        return (Read-Host -Prompt $PromptMessage)
    }

    return $CurrentValue
}

function Ensure-Directory {
    param(
        [string]$Path
    )

    if (-not [string]::IsNullOrWhiteSpace($Path)) {
        $resolved = Resolve-Path -Path $Path -ErrorAction SilentlyContinue
        if ($null -eq $resolved) {
            New-Item -ItemType Directory -Path $Path -Force | Out-Null
            $resolved = Resolve-Path -Path $Path
        }

        return $resolved.ProviderPath
    }
}

$scriptRoot = Split-Path -Path $MyInvocation.MyCommand.Path -Parent
$repoRoot = Resolve-RepoRoot -ScriptPath $MyInvocation.MyCommand.Path

if (-not (Get-Command node -ErrorAction SilentlyContinue)) {
    throw "Node.js is not installed or not available in PATH. Install Node.js 20 before running the runner."
}

$nodeVersion = (& node --version).Trim()
if ($nodeVersion -notmatch '^v20\.') {
    Write-Warning "The runner targets Node.js 20. Detected version: $nodeVersion"
}

$HostUrl = Get-ValueOrPrompt -CurrentValue $HostUrl -PromptMessage "Enter AUTOMN_HOST_URL"
$RunnerId = Get-ValueOrPrompt -CurrentValue $RunnerId -PromptMessage "Enter AUTOMN_RUNNER_ID"

if ([string]::IsNullOrWhiteSpace($EndpointUrl) -and [string]::IsNullOrWhiteSpace($PublicUrl)) {
    $EndpointUrl = Get-ValueOrPrompt -CurrentValue $EndpointUrl -PromptMessage "Enter AUTOMN_RUNNER_ENDPOINT_URL (leave empty to provide PUBLIC_URL instead)"
    if ([string]::IsNullOrWhiteSpace($EndpointUrl)) {
        $PublicUrl = Get-ValueOrPrompt -CurrentValue $PublicUrl -PromptMessage "Enter AUTOMN_RUNNER_PUBLIC_URL"
        $EndpointPath = Get-ValueOrPrompt -CurrentValue $EndpointPath -PromptMessage "Enter AUTOMN_RUNNER_ENDPOINT_PATH"
    }
}

$Secret = Get-ValueOrPrompt -CurrentValue $Secret -PromptMessage "Enter AUTOMN_RUNNER_SECRET (press Enter to skip and use the UI)" -IsSecret

if (-not $Port) {
    $portInput = Get-ValueOrPrompt -CurrentValue $null -PromptMessage "Enter AUTOMN_RUNNER_PORT (press Enter for default 3030)"
    if (-not [string]::IsNullOrWhiteSpace($portInput)) {
        if ($portInput -as [int]) {
            $Port = [int]$portInput
        } else {
            throw "AUTOMN_RUNNER_PORT must be a valid integer."
        }
    }
}

$NodeExecutable = Get-ValueOrPrompt -CurrentValue $NodeExecutable -PromptMessage "Enter custom Node executable path (press Enter to use PATH)"
$PythonExecutable = Get-ValueOrPrompt -CurrentValue $PythonExecutable -PromptMessage "Enter custom Python executable path (press Enter to use PATH)"
$PowerShellExecutable = Get-ValueOrPrompt -CurrentValue $PowerShellExecutable -PromptMessage "Enter custom PowerShell executable path (press Enter to use PATH)"

if (-not $StateDir) {
    $StateDir = Join-Path -Path $scriptRoot -ChildPath "state"
}
if (-not $ScriptsDir) {
    $ScriptsDir = Join-Path -Path $scriptRoot -ChildPath "scripts"
}
if (-not $WorkDir) {
    $WorkDir = Join-Path -Path $scriptRoot -ChildPath "script_workdir"
}

$StateDir = (Ensure-Directory -Path $StateDir)
$ScriptsDir = (Ensure-Directory -Path $ScriptsDir)
$WorkDir = (Ensure-Directory -Path $WorkDir)

Push-Location -Path $repoRoot
try {
    if (-not $SkipNpmInstall) {
        Write-Host "Installing production dependencies (npm ci --omit=dev)..."
        npm ci --omit=dev
    } else {
        Write-Host "Skipping npm installation as requested."
    }

    $env:NODE_ENV = "production"
    $env:AUTOMN_HOST_URL = $HostUrl
    $env:AUTOMN_RUNNER_ID = $RunnerId
    if (-not [string]::IsNullOrWhiteSpace($EndpointUrl)) {
        $env:AUTOMN_RUNNER_ENDPOINT_URL = $EndpointUrl
        Remove-Item Env:AUTOMN_RUNNER_PUBLIC_URL -ErrorAction SilentlyContinue
        Remove-Item Env:AUTOMN_RUNNER_ENDPOINT_PATH -ErrorAction SilentlyContinue
    } else {
        $env:AUTOMN_RUNNER_PUBLIC_URL = $PublicUrl
        $env:AUTOMN_RUNNER_ENDPOINT_PATH = $EndpointPath
        Remove-Item Env:AUTOMN_RUNNER_ENDPOINT_URL -ErrorAction SilentlyContinue
    }

    if ($Port) {
        $env:AUTOMN_RUNNER_PORT = [string]$Port
    } else {
        Remove-Item Env:AUTOMN_RUNNER_PORT -ErrorAction SilentlyContinue
    }

    if (-not [string]::IsNullOrWhiteSpace($Secret)) {
        $env:AUTOMN_RUNNER_SECRET = $Secret
    } else {
        Remove-Item Env:AUTOMN_RUNNER_SECRET -ErrorAction SilentlyContinue
    }

    $env:AUTOMN_RUNNER_STATE_DIR = $StateDir
    $env:AUTOMN_RUNNER_SCRIPTS_DIR = $ScriptsDir
    $env:AUTOMN_RUNNER_WORKDIR = $WorkDir

    if (-not [string]::IsNullOrWhiteSpace($NodeExecutable)) {
        $env:AUTOMN_RUNNER_NODE_PATH = $NodeExecutable
    } else {
        Remove-Item Env:AUTOMN_RUNNER_NODE_PATH -ErrorAction SilentlyContinue
    }

    if (-not [string]::IsNullOrWhiteSpace($PythonExecutable)) {
        $env:AUTOMN_RUNNER_PYTHON_PATH = $PythonExecutable
    } else {
        Remove-Item Env:AUTOMN_RUNNER_PYTHON_PATH -ErrorAction SilentlyContinue
    }

    if (-not [string]::IsNullOrWhiteSpace($PowerShellExecutable)) {
        $env:AUTOMN_RUNNER_POWERSHELL_PATH = $PowerShellExecutable
        $env:AUTOMN_POWERSHELL_PATH = $PowerShellExecutable
    } else {
        Remove-Item Env:AUTOMN_RUNNER_POWERSHELL_PATH -ErrorAction SilentlyContinue
        Remove-Item Env:AUTOMN_POWERSHELL_PATH -ErrorAction SilentlyContinue
    }

    $effectivePort = if ($Port) { $Port } else { 3030 }

    Write-Host "Starting Automn runner..." -ForegroundColor Green
    Write-Host "Host URL: $HostUrl"
    Write-Host "Runner ID: $RunnerId"
    Write-Host "Port: $effectivePort"
    if (-not [string]::IsNullOrWhiteSpace($EndpointUrl)) {
        Write-Host "Endpoint URL: $EndpointUrl"
    } else {
        Write-Host "Public URL: $PublicUrl"
        Write-Host "Endpoint Path: $EndpointPath"
    }
    if (-not [string]::IsNullOrWhiteSpace($Secret)) {
        Write-Host "Secret provided via environment variable. The UI secret form will be disabled."
    } else {
        Write-Host "No secret provided. Use the runner UI at http://localhost:$effectivePort/ to enter it after launch."
    }
    $nodeSummary = if ([string]::IsNullOrWhiteSpace($NodeExecutable)) { "PATH default" } else { $NodeExecutable }
    $pythonSummary = if ([string]::IsNullOrWhiteSpace($PythonExecutable)) { "PATH default" } else { $PythonExecutable }
    $powerShellSummary = if ([string]::IsNullOrWhiteSpace($PowerShellExecutable)) { "PATH default" } else { $PowerShellExecutable }
    Write-Host "Node executable: $nodeSummary"
    Write-Host "Python executable: $pythonSummary"
    Write-Host "PowerShell executable: $powerShellSummary"

    & node "runner/service.js"
}
finally {
    Pop-Location
}
